### ISSUE TITLE
Configuration should be moved to Salt

### ISSUE THREAD

**Issue by topeju** [topeju/autopi_mqtt#1]
At the moment, the MQTT broker connection information needs to be edited by hand into `my_mqtt_cache.py`, which is less than ideal from a version control point of view. Salt has configuration management, but I haven't yet figured out how to use it -- if possible, the configuration should be moved there instead.

**Comment by dasTholo** [comment]
I think I walked into that mistake.
```
defaultEndpoint = {
    "client_id": "AutoPi",
    "clean_session": True,
    #"userdata": None,
    #"protocol": "MQTTv311",
    #"transport": "tcp",
    "server": "mqtt.local",
    "port": 1883,
    "keepalive": 60,
    #"bind_address": "",
    "topic_root": "AutoPi/", # Note: this should have a slash at the end
    "qos": 2, # 1 or 2 is probably recommended, 0 will most likely lose items if connectivity is intermittent
    "retain": False
}
```
And at class MqttCache(object):
```
endpoint = self.options.get("endpoint", defaultEndpoint)

# Publish the data to MQTT
mqttClient = mqtt.Client(client_id=endpoint['client_id'], clean_session=endpoint['clean_session'])
```
Syslog print
_May  8 09:21:52 autopi-xxsalt-minion[296]: [ERROR   ] Recurring exception (62 times) in worker thread 'upload' while running workflow for message: {'handler': 'upload'}
May  8 09:21:52 autopi-xxsalt-minion[296]: Traceback (most recent call last):
May  8 09:21:52 autopi-xxsalt-minion[296]:   File "/var/cache/salt/minion/extmods/utils/messaging.py", line 162, in do_work
May  8 09:21:52 autopi-xxxsalt-minion[296]:     self._call_hook_for(message, "workflow", message)
May  8 09:21:52 autopi-xxsalt-minion[296]:   File "/var/cache/salt/minion/extmods/utils/messaging.py", line 433, in _call_hook_for
May  8 09:21:52 autopi-xxsalt-minion[296]:     return True, func(*args, **kwargs)
May  8 09:21:52 autopi-xxsalt-minion[296]:   File "/var/cache/salt/minion/extmods/utils/messaging.py", line 271, in simple_workflow
May  8 09:21:52 autopi-xxsalt-minion[296]:     _, result = self._call_hook_for(message, "handler", *args, **kwargs)
May  8 09:21:52 autopi-xxsalt-minion[296]:   File "/var/cache/salt/minion/extmods/utils/messaging.py", line 433, in _call_hook_for
May  8 09:21:52 autopi-xxsalt-minion[296]:     return True, func(*args, **kwargs)
May  8 09:21:52 autopi-xxsalt-minion[296]:   File "/var/cache/salt/minion/extmods/utils/messaging.py", line 571, in synchronizer
May  8 09:21:52 autopi-xxsalt-minion[296]:     return func(*args, **kwargs)
May  8 09:21:52 autopi-xxsalt-minion[296]:   File "/opt/autopi/salt/engines/my_mqtt_manager.py", line 113, in upload_handler
May  8 09:21:52 autopi-xxsalt-minion[296]:     ret["pending"] = cache.upload_pending()
May  8 09:21:52 autopi-xxsalt-minion[296]:   File "/opt/autopi/salt/utils/my_mqtt_cache.py", line 612, in upload_pending
May  8 09:21:52 autopi-xxsalt-minion[296]:     self.PENDING_QUEUE)  # Remember this call will raise exception upon server error
May  8 09:21:52 autopi-xxsalt-minion[296]:   File "/opt/autopi/salt/utils/my_mqtt_cache.py", line 356, in _upload_batch_continuing
May  8 09:21:52 autopi-xxsalt-minion[296]:     res = self._upload_batch(queue)  # Remember this call will raise exception upon server error
May  8 09:21:52 autopi-xxxsalt-minion[296]:   File "/opt/autopi/salt/utils/my_mqtt_cache.py", line 560, in _upload_batch
May  8 09:21:52 autopi-xxsalt-minion[296]:     ok, msg = self._upload(payload)  # Remember this call will raise exception upon server error
May  8 09:21:52 autopi-xxsalt-minion[296]:   File "/opt/autopi/salt/utils/my_mqtt_cache.py", line 264, in _upload
May  8 09:21:52 autopi-xxsalt-minion[296]:     mqttClient = mqtt.Client(endpoint["client_id"], clean_session=endpoint["clean_session"])
May  8 09:21:52 autopi-xxsalt-minion[296]: KeyError: 'client_id'_

My local test script will run with
```
options = {"endpoint": {
        "client_id": "aus options",
        "clean_session": True,
        # "userdata": None,
        # todo add connection options
        #"protocol": "MQTTv311",
        # "transport": "tcp",
        # ssl is still set to Insecure! Todo add vert files
        "ssl": False,
        "server": "xxx.xxx.org",
        "port": 1883,
        "username": "xxx",
        "password": "xxx",
        "keepalive": 60,
        # "bind_address": "",
        "topic_root": "autopi/",  # Note: this should have a slash at the end
        "qos": 1,  # 1 or 2 is probably recommended, 0 will most likely lose items if connectivity is intermittent
        "retain": False
        }}
endpoint = options.get("endpoint", defaultEndpoint)
mqttClient = mqtt.Client(client_id=endpoint["client_id"], clean_session=endpoint["clean_session"])
```

I don't understand the setting window either. Since it accepts neither json nor yaml style or varname=var
